baseURL = "https://nullc.at/"
title = "nullc.at"
author = "NullCat"
HasCJKLanguage = true
DefaultContentLanguage = "ja"
languageCode = "ja-jp"
enableRobotsTXT = true
pluralizeListTitles = false
markup.highlight.noClasses = false

[Params]
dateformat = "2006/01/02"
description = "ぬるきゃっとのホームページ"

[taxonomies]
tag = "tags"
category = "categories"
archive = "archives"
